### ISSUE TITLE
dedupe cannot handle the complex object types

### ISSUE THREAD

**Issue by Jiazhi-Wong** [seriousManual/dedupe#23]
### replay

```
var arr1 = [{a: 1, b: 2}, {a: 1, b: 2}]
var arr2 = [{a: 1, b: 2}, {a: 2, b: 1}]
console.log(dedupe(arr1)) // [{a: 1, b: 2}]
console.log(dedupe(arr2)) // [{a: 1, b: 2}, {a: 2, b: 1}]
```

The expected result is `arr2` also return `[{a: 1, b: 2}]`.

**Comment by seriousManual** [comment]
This is correct.
dedupe uses `JSON.stringify` under the hood to do serializations, which does respect the insertion order.

This behaviour though is not specified, in objects the order is not guaranteed and it is not a good idea to rely on it.

You can specify your own hasher though, which takes the order into consideration.
